### ISSUE TITLE
how to start the front-end part

### ISSUE THREAD

**Issue by GavinLiao89** [Mowgli9/ERC1155-NFT-Marketplace#2]
Hi, I was wondering after compile and deploy the contracts, how do I start the front-end part? I tried `npm start` but it won't work.
Is there any step by step tutorial to follow?
Thanks a lot.

**Comment by Mowgli9** [comment]
Hello, I was stupid in the frontend side with no knowledge, I just create a normal HTML /css / Javascript , you need to click on the index.html, also change the abis etc ..

**Comment by GavinLiao89** [comment]
I understood, thank you for answering!
